# https://github.com/marketplace/actions/go-test-coverage
name: Go test coverage check
permissions:
  contents: read
on: 
  pull_request:
  #push:
  #  branches-ignore:
  #    - master
  #    - main

jobs:
  test:
    strategy:
      matrix:
        go: ['1.21']
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest, windows-latest]
    name: test and coverage
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
    
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/Pacobart/terraform-cloud-workspace-collector
          #threshold-file: 80 # The minimum coverage that each file should have
          #threshold-package: 80 # The minimum coverage that each package should have
          #threshold-total: 95 # The minimum total coverage project should have
          git-branch: badges
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}