# https://github.com/marketplace/actions/github-tag
name: Version
permissions:
  contents: write
on:
  push:
    branches:
      - main
      - binaries
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Generate the artifacts
        uses: skx/github-action-build@master
        with:
          builder: .github/build
      - name: show me directory
        run: |
              ls -la
              ls -la bin/
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.build.steps.tag_version.outputs.new_tag }}
          args: 'bin/tf-collect*'